# Generated by Django 4.2 on 2024-06-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adreça', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OrdreReparacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inici', models.DateTimeField()),
                ('data_fi', models.DateTimeField(blank=True, null=True)),
                ('descripció', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('any', models.IntegerField()),
                ('matrícula', models.CharField(max_length=15, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='taller.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrdreReparacioArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.article')),
                ('ordre_reparacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.ordrereparacio')),
            ],
        ),
        migrations.AddField(
            model_name='ordrereparacio',
            name='articles',
            field=models.ManyToManyField(through='taller.OrdreReparacioArticle', to='taller.article'),
        ),
        migrations.AddField(
            model_name='ordrereparacio',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_reparacio', to='taller.vehicle'),
        ),
    ]
